services:
  postgres:
    image: postgres:15-alpine
    container_name: unifor-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: unifor
      POSTGRES_PASSWORD: unifor123
      POSTGRES_DB: matriz_curricular
#    volumes:
#      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unifor -d matriz_curricular"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: unifor-keycloak
    ports:
      - "8180:8080"
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080; echo -e \"GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n\" >&3; cat <&3 | grep -q \"200 OK\""]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: unifor-backend
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/matriz_curricular
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/unifor
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: unifor-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
